version: '3.8'

services:
  api_test_db:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-test}
    volumes:
      - ./postgres/:/var/lib/postgresql/data:rw
      - /media/admi/4cc1c42d-1a9c-4f12-b14d-0688bddfc95d/home/admi/Документы/post_air/:/var/lib/postgresql/backups:rw
    networks:
      yaparser:
        ipv4_address: 192.168.223.2

  api_test_app:
    container_name: ${PROJECT_NAME}_app
    build:
      context: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app/:/var/www/
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    depends_on:
      - api_test_db
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.223.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=PhpServerBase"
    networks:
      yaparser:
        ipv4_address: 192.168.223.3
    extra_hosts:
      - "host.docker.internal:192.168.223.1"

  nginx_api_test:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/
      - ./nginx/logs:/var/www/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - api_test_app
    depends_on:
      - api_test_app
      - api_test_db
    networks:
      yaparser:
        ipv4_address: 192.168.223.4

networks:
  yaparser:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.223.0/24