api_platform:
    title: Test API
    version: 1.0.0
    formats:
        jsonopenapi: ['application/vnd.openapi+json']
        json: ['application/json']
        jsonld: ['application/ld+json']
        formdata: ["multipart/form-data"]
    docs_formats:
        jsonopenapi: ['application/vnd.openapi+json']
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false

